### PR TITLE
Use jsoncolor package to colorize JSON bodies

### PR DESCRIPTION
**Pull request by nwidger**
This PR uses the jsoncolor package to colorize JSON bodies.  It
changes the imports to use my forked version of
github.com/jroimartin/gocui which includes a small patch to support
zero-parameter CSI escape sequences.  I have submitted a PR upstream:

https://github.com/jroimartin/gocui/pull/98

Once that PR is merged the import can be switched back to
github.com/jroimartin/gocui if desired.

### CODE REVIEW

**Comment by Benaiah** [comment]
@nwidger man, I wish I was better at googling. I've spent the last couple days building https://github.com/benaiah/pretty-print to do the same thing as jsoncolor. :stuck_out_tongue_closed_eyes: I guess I got some experience with Go's `json` package, if nothing else.

Personally, I'd prefer we wait for upstream to merge the CSI patch, rather than changing the requests, particularly as @jroimartin has been pretty active on gocui today, so it shouldn't take long to merge.

**Comment by nwidger** [comment]
No problem, https://github.com/jroimartin/gocui/pull/98 seems like it should be a quick merge.  Once that happens I'll change the import path back on this PR.

**Comment by nwidger** [comment]
Yup, I'll get to that in a few.

**Comment by nwidger** [comment]
How do things look?  Let me know if I should change anything else.

**Comment by asciimoo** [comment]
Awesome, thanks.

**Comment by nwidger** [comment]
No problem!  Do you think the screencast in the README should be updated?

**Comment by asciimoo** [comment]
Ah, yes, it is very outdated.

**Pull request merged**
