### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by Nevon**
I thought this was a really neat tool, but I don't currently have go set up on my computer, so I set it up to run in docker and published an image here: https://hub.docker.com/r/nevon/wuzz/

I would much rather have that be automatically built whenever there's a push to master in here, though, so I thought I'd do a PR and see if you were interested. If you are, all you have to do in order to have an automated build is to go to docker hub, click the "automated build" thing, choose this repo and you should be good to go. By default it will build and tag with `latest` for master, and tag with `branch-name` for branch pushes.

It's nothing special, really, the only weird thing is that I had to sleep for a tiny duration before running wuzz, because otherwise I would get an error from gocui. I think it has something to do with `docker run -it` running the command before actually attaching.

### CODE REVIEW

**Comment by antham** [comment]
Don't you think it would be better to have binaries in release part of github ? I tried with gox for instance, I built binaries for common platforms with no efforts.

**Comment by Nevon** [comment]
Yeah, for sure, I just assumed that the author wasn't interested in providing built binaries, so distributing a docker image was the simplest way to get something that can run more or less anywhere.

It would be nice to have both, though. While it obviously sucks to have to suck down 200mb of stuff just to run what should be a tiny binary, a nice upside is that you automatically get the latest version.

**Comment by antham** [comment]
I guess, it's possible to reduce the container size cause we only have a single binary, it needs few dependencies to run.

**Comment by jpsnbugzz** [comment]
np

**Comment by yardenshoham** [comment]
If there's any interest, I can create a PR utilizing modern Docker best practices. @asciimoo?

**Comment by asciimoo** [comment]
@yardenshoham thanks for the offer.
I'm not really using docker and we have pre-built binaries and also distro packages for debian/ubuntu/arch, but I'm not against this feature if there is demand for it.

**Comment by yardenshoham** [comment]
So, if I create a PR, you'll accept it?

**Comment by asciimoo** [comment]
> So, if I create a PR, will you accept it?

Sure, thanks!

**Pull request closed without merging**
