### PR TITLE
Document 'load request' feature, bind to 'ctrl+f'

### PR DESCRIPTION
**Pull request by colinta**
I arbitrarily left the json file loading in two places, maybe `loadRequest` should take a file name?

Chose `ctrl+f` to load a file because it was close to `ctrl+e`, but in hindsight maybe should be `ctrl+o`?

Thoughts?

### CODE REVIEW

**Comment by asciimoo** [comment]
Ohi, super useful feature!

> I arbitrarily left the json file loading in two places, maybe loadRequest should take a file name?

Good idea

> Chose ctrl+f to load a file because it was close to ctrl+e, but in hindsight maybe should be ctrl+o?

`ctrl+f` is ok for me


Also, it would be good to add a bit more sophisticated error handling. Now if I specify a nonexistent file, wuzz crashes. Could you fix that?

**Comment by colinta** [comment]
Good call on the crash, I never tested that!  It would be nice to show an error message, is there somewhere else where that happens, so I can duplicate that behavior?

Two more commits, moved more code into `func LoadRequest` and the app won't crash if the file doesn't exist - though it still will if the json is unreadable.  I'll convert that to an error message as well.

**Comment by colinta** [comment]
Got it, found some code int `SubmitRequest` that will work great, I'll show the error in the response section.

**Comment by colinta** [comment]
K, this should be good to go!

By the way, I've been playing with a port of this app in Swift and using a ReactJS-like terminal framework I'm hacking on for fun these days: https://github.com/colinta/Ashen/blob/master/Sources/Demo/Suss.swift

**Pull request merged**
